20210131

diff --git a/init.d/udev_retry b/init.d/udev_retry
--- a/init.d/udev_retry
+++ b/init.d/udev_retry
@@ -4,6 +4,8 @@
 #
 # Description : Udev cold-plugging script (retry)
 #
+# Version     : LFS 7.0
+#
 ########################################################################
 
 ### BEGIN INIT INFO
@@ -20,48 +22,36 @@
 #                      device nodes
 ### END INIT INFO
 
-. /lib/lsb/init-functions
+soource /lib/lsb/init-functions
 
 case "${1}" in
-   start)
-      log_info_msg "Retrying failed uevents, if any..."
-
-      # As of udev-186, the --run option is no longer valid
-      #rundir=$(/sbin/udevadm info --run)
-      rundir=/run/udev
-      # From Debian: "copy the rules generated before / was mounted
-      # read-write":
-
-      for file in ${rundir}/tmp-rules--*; do
-         dest=${file##*tmp-rules--}
-         [ "$dest" = '*' ] && break
-         cat $file >> /etc/udev/rules.d/$dest
-         rm -f $file
-      done
-
-      # Re-trigger the uevents that may have failed,
-      # in hope they will succeed now
-      /bin/sed -e 's/#.*$//' /etc/sysconfig/udev_retry | /bin/grep -v '^$' | \
-      while read line ; do
-         for subsystem in $line ; do
-            /sbin/udevadm trigger --subsystem-match=$subsystem --action=add
-         done
-      done
-
-      # Now wait for udevd to process the uevents we triggered
-      if ! is_true "$OMIT_UDEV_RETRY_SETTLE"; then
-         /sbin/udevadm settle
-      fi
-
-      evaluate_retval
-      ;;
-
-   *)
-      echo "Usage ${0} {start}"
-      exit 1
-      ;;
+	start)	log_info_msg "Retrying failed uevents, if any..."
+		# As of udev-186, the --run option is no longer valid
+		#rundir=$(/sbin/udevadm info --run)
+		rundir=/run/udev
+		# From Debian: "copy the rules generated before / was mounted
+		# read-write":
+		for file in ${rundir}/tmp-rules--*; do
+			dest=${file##*tmp-rules--}
+			[ "$dest" = '*' ] && break
+			cat $file >> /etc/udev/rules.d/$dest
+			rm -f $file
+		done
+		# Re-trigger the uevents that may have failed,
+		# in hope they will succeed now
+		/bin/sed -e 's/#.*$//' /etc/sysconfig/udev_retry | /bin/grep -v '^$' | \
+		while read line ; do
+			for subsystem in $line ; do
+				/sbin/udevadm trigger --subsystem-match=$subsystem --action=add
+			done
+		done
+		# Now wait for udevd to process the uevents we triggered
+		if ! is_true "$OMIT_UDEV_RETRY_SETTLE"; then /sbin/udevadm settle; fi
+		evaluate_retval
+	;;
+	*)	echo "Usage ${0} {start}"
+		exit 1
+	;;
 esac
-
 exit 0
-
 # End udev_retry
